application: searchvinyls
version: 1
runtime: python
api_version: 1

handlers:
  - url: /images
    static_dir: images
  - url: .*
    script: main.py
error_handlers:
  - file: templates/default_error.html