application: searchvinyls
version: 3
api_version: 1
runtime: python27
threadsafe: false
handlers:
  - url: /images
    static_dir: images
  - url: /styles
    static_dir: styles
  - url: /scripts
    static_dir: templates/scripts
  - url: /
    script: main.app
  - url: /result
    script: main.app
  - url: /about
    script: main.app
  - url: /api/mostwanted
    script: api.app
  - url: /api/search
    script: api.app
  - url: /contact
    script: main.app
  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico
    expiration: "1d"
  - url: /index/cron
    script: cron_search.app
    login: admin
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt
  - url: /index/task
    script: search_task.app
    login: admin
  - url: /index/index
    script: index_task.app
    login: admin

error_handlers:
  - file: templates/default_error.html